### ISSUE TITLE
Build Error with libsigc++ 2.62

### ISSUE THREAD

**Issue by slackhead** [amsynth/amsynth#20]
I'm trying to build on slackware64 14.2 and get this error:

/usr/include/gtkmm-2.4/gtkmm/treeview.h:2289:5:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:177:72: error: ‘operator()’ not defined
       return (typed_rep->functor_).SIGC_WORKAROUND_OPERATOR_PARENTHESES<type_trait_take_t<T_arg1>,

Any ideas how to fix it?

**Comment by nixxcode** [comment]
Please try `./configure CXXFLAGS='-std=c++11'` - not sure if it will work but worth a shot

**Comment by slackhead** [comment]
Thanks. That works great.
